/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlerMain: typeof import('./src/components/pages/controller-main/controler-main.vue')['default']
    ControllerMain: typeof import('./src/components/pages/controller-main/controller-main.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiHeader: typeof import('./src/components/pages/ui-header.vue')['default']
    UiSidebar: typeof import('./src/components/pages/ui-sidebar.vue')['default']
    UiSidepar: typeof import('./src/components/pages/ui-sidepar.vue')['default']
    UserEdit: typeof import('./src/components/user-edit.vue')['default']
    UserList: typeof import('./src/components/user-list.vue')['default']
  }
}
